FILESEXTRAPATHS_append := "${THISDIR}/files:"
SRC_URI_append =" file://breakpad-ucontext.patch"
SRC_URI_append_dunfell =" file://src-client-linux-handler-exception_handler.cc-rename.patch"
SRC_URI_append =" file://breakpad_processname.patch"
SRC_URI_append = " file://add-stackwalk-common-to-makefile.patch "
SRC_URI += "${@bb.utils.contains('DISTRO_FEATURES', 'mixmode', 'file://breakpad_mixedmode_fpregs.patch', '', d)}"
